version: '3.7'

networks:
  currency-network:

services:
  api-gateway:
    image: docker.io/kvandana/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.FETCHREGISTRY: "true"

  naming-server:
    image: docker.io/kvandana/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-exchange:
    image: docker.io/kvandana/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
      - "8001:8000"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.FETCHREGISTRY: "true"
    networks:
      - currency-network

  currency-conversion:
    image: docker.io/kvandana/currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      EUREKA.CLIENT.FETCHREGISTRY: "true"

#  zipkin-server:
#    image: openzipkin/zipkin:2.23
#    mem_limit: 300m
#    ports:
#      - "9411:9411"
#    networks:
#      - currency-network
#    environment:
#      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#    depends_on:
#      - rabbitmq
#    restart: always
#
#  rabbitmq:
#    image: rabbit:3.8.12-management
#    mem_limit: 300m
#    ports:
#      - "5672:5762"
#      - "15672:15672"
#    networks:
#      - currency-network